services:
  db:
    image: postgres:15
    container_name: product_db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  product-microservice:
    build: .
    container_name: product_microservice
    ports:
      - "8001:8001"
    env_file:
      - .env
    depends_on:
      - db

volumes:
  db_data: